version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 166232
      MYSQL_DATABASE: blue
      MYSQL_USER: root
      MYSQL_PASSWORD: 166232
    

  redis:
    image: redis:latest

  blue:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
